name: build

on:
  push:
    branches: '*'
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Prepare cached external dependencies
        uses: actions/cache@v2
        with:
          key: addons_external_${{ hashFiles('.github/actions/download-externals-action/download.sh') }}
          path: |
            external
      - name: Download build dependencies
        uses: ./.github/actions/download-externals-action

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build the project
        run: ./gradlew assembleDebug
      - name: Upload APKs
        uses: actions/upload-artifact@v2
        with:
          retention-days: 60
          name: apk
          path: |
            */build/outputs/apk/**/*apk
